FROM lsiobase/alpine:arm64v8-3.8

COPY qemu-aarch64-static /usr/bin

RUN \
  echo "installing packages" && \
  apk add --no-cache \
    murmur \
    icu-libs

COPY root/ /
EXPOSE 64738
VOLUME /config
