version: '3'

services:
  murmur:
    container_name: 'murmur'
    image: 'redstonekasi/murmur'

    ports:
      - '64738:64738/tcp'
      - '64738:64738/udp'

    volumes:
      - './config:/config'

    restart: 'unless-stopped'
