FROM alpine AS qemu

ENV QEMU URL https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-aarch64.tar.gz
RUN apk add curl && curl -L ${QEMU_URL} | tar zxvf - -C . --strip-components 1

FROM lsiobase/alpine:arm64v8-3.8

COPY --from=qemu qemu-aarch64-static /usr/bin

RUN \
  echo "installing packages" && \
  apk add --no-cache \
    murmur \
    icu-libs

COPY root/ /
EXPOSE 64738
VOLUME /config
